### ISSUE TITLE
Addition of New 404 Template

### ISSUE THREAD

**Issue by Ritika122001** [tsparticles/404-templates#33] opened 2022-10-03 08:16 UTC
Kindly assign the issue!!
Thank You.

**Comment by Ritika122001** [comment] 2022-10-03 09:48
Hey @matteobruni. Could you please assign this issue under the Hacktoberfest label?

**Comment by matteobruni** [comment] 2022-10-03 09:49
> Hey @matteobruni. Could you please assign this issue under the Hacktoberfest label?

It's not mandatory for Hacktoberfest, it counts only PRs, but no problem anyway

**Comment by ShrutiJ-01** [comment] 2022-10-04 03:21
I'd like to raise a PR for a new 404 template. Could you please assign it to me as well?

**Comment by anmolrajsoni15** [comment] 2022-10-04 11:02
I have an amazing animated page design.
@matteobruni I would really appreciate it if you could assign me this issue so that can I can start contributing to this repo and generate a successfull PR.
Thank you and have a great Hacktoberfest ['22!]

**Comment by anmolrajsoni15** [comment] 2022-10-04 11:34
Hello @matteobruni I am ready with my design. Please assign this issue so that I can generate a successful PR.
Thank You

**Comment by anmolrajsoni15** [comment] 2022-10-04 11:59
Thank You @matteobruni for assigning the issue to me. I have successfully generated the PR. Kindly accept it.

**Comment by matteobruni** [comment] 2022-10-04 12:03
I'm closing this issue, it's a duplicate of #18 without all the requirements.

**Closed by matteobruni** 2022-10-04 12:03 UTC
Labels: Hacktoberfest
